<!--  
<div class=foot>
<h2 class="title">Kontaktirajte nas</h2>
<p>Email:hfh@gmail.com</p>

<ul>
<li>Links</li>
<li><a href=""></a></li>
<li><a href=""></a></li>
<li><a href=""></a></li>
<li><a href=""></a></li>
</ul>
</div>  -->
<div class=foot>
<ol type="A">
			
		<li><a href="#" class="fa fa-facebook"></a></li><br>
		<li><a href="#" class="fa fa-twitter"></a></li><br>
		<li><a href="#" class="fa fa-google-plus"></a></li>
</ol>

</div>
