<!Doctype html>
<html>
<head>

<link rel="stylesheet" type="text/css" href="<?php echo $resurce_path ?>css/style.css">
<script type="text/javascript " src="<?php echo $resurce_path ?>js/functional.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>

<?php echo $this->header;?>

<div class="wrap">
    <div class="content">
    <?php echo $this->index; ?>
        <?php echo $this->content; ?>
        
    </div>

</div>
<?php echo $this->footer;?>


</body>
</html>