<table summary="5 day for Beograd">
 <thead>
<tr> 
<th width="207">Beograd</th>
<th width="102" style="text-align:center">
  Ponedeljak <br>
  01.07.</th>
<th width="102" style="text-align:center">
  Utorak <br>
  02.07.</th>
<th width="102" style="text-align:center">
  Sreda  <br>
  03.07.</th>
<th width="102" style="text-align:center">
  Cetvrtak <br>
  04.07.</th>
<th width="102" style="text-align:center">
  Petak <br>
  05.07.</th>
<th width="102" style="text-align:center">
  Subota <br>
  06.07.</th>
</tr>
</thead>


<tbody>


<tr>
<td class="levo">Маx. temeperatura: (°C)</td>
<td style="text-align:center">35</td>
<td style="text-align:center">29</td>
<td style="text-align:center">29</td>
<td style="text-align:center">30</td>
<td style="text-align:center">29</td>
<td style="text-align:center">27</td>
</tr>

<tr>
<td class="levo">Мin. temperatura: (°C)</td>
<td style="text-align:center">-</td>
<td style="text-align:center">20</td>
<td style="text-align:center">17</td>
<td style="text-align:center">18</td>
<td style="text-align:center">18</td>
<td style="text-align:center">19.5</td>
</tr>

<tr> 
 <td class="levo">Pojava:</td>
<td style="text-align:center;"><img src="../img/vedro.gif" alt="Pojava"></td>
<td style="text-align:center;"><img src="../img/poblacno.gif" alt="Pojava"></td>
<td style="text-align:center;"><img src="../img/vedro.gif" alt="Pojava"></td>
<td style="text-align:center;"><img src="../img/uoblacno.gif" alt="Pojava"></td>
<td style="text-align:center;"><img src="../img/suncano.gif" alt="Pojava"></td>
<td style="text-align:center;"><img src="../img/ppljuskovi.gif" alt="Pojava"></td>
</tr>


<tr> 
<td colspan="9">
  <p>Normale:</p>
<img src="../img/grafik.png" >
</td>
</tr>
</tbody>
</table>