<table width="90%">
    <thead>
	<tr>
    <th>Prognozirane srednje vrednosti <span>minimalne</span> i <span>makmimalne</span>temperature</th>
    <th>Прогнозирана средња месечна количина падавина</th>
  </tr>
  </thead>
  <tbody><tr>
    <td><img src="../img/temp.gif" alt="srednja mesecna minimalna i maksimalna temperatura vazduha"></td>
    <td><img src="../img/pada.gif" alt="srednja mesecna kolicina padavina"></td>
  </tr>
</tbody>
</table>
<div class="text">
<p>
        
    <strong>
    JUN 2019: U celoj Srbiji topliji i vlazniji jun.  Moguca je pojava toplotnog talasa.
     </strong>
</p>
<p style="width:95%">    
Srednja minimalna temperatura vazduha u junu imace vrednosti iznad visegodinjeg proseka, pri cemu ce njena vrednost u proseku biti vica za oko 0.7ºS u odnosu na visegodisnji prosek. U Beogradu i siroj okolini predvidja se vrednost junske srednje minimalne temperature vazduha od 17.1ºS.
Srednja maksimalna temperatura vazduha u junu bice u granicama visegodisnjeg proseka, sa vrednostima u proseku visim za oko 0.1ºS u odnosu na visegodisnji prosek. U Beogradu i siroj okolini srednja maksimalna temperatura vazduha tokom juna bice oko 27.0ºS.
U celoj Srbiji mesecna suma padavina tokom juna bice iznad visegodisnjeg proseka sa vrednostima u proseku visim za oko 20 mm; u Jugozapadnoj Srbiji iznad visegodisnjeg proseka sa vrednostima u proseku visim za 20 mm do 50 mm u odnosu na visegodisnji prosek. U Beogradu i siroj okolini junska suma padavina  iznosice oko 80 mm.	
</p>

<strong>
JUL 2019: Toplotni talasi. Topliji i prosecno suv jul.
</strong>
<p style="width:95%">
Srednja minimalna temperatura vazduha u julu imace vrednosti iznad visegodišnjeg proseka, pri cemu ce njena vrednost u proseku biti visa za oko 0.9ºS u odnosu na visegodisnji prosek. 
U Beogradu i siroj okolini predvidja se vrednost julske srednje minimalne temperature vazduha od 18.4ºS. 
Srednja maksimalna temperatura vazduha u julu bice iznad visegodisnjeg proseka, sa vrednostima u proseku visim za oko 1.0ºS u odnosu na visegodišnji prosek. 
U Beogradu i široj okolini srednja maksimalna temperatura vazduha tokom jula bice oko 29.6ºS. Mesecna suma padavina tokom jula bice u granicama visegodisnjeg proseka sa vrednostima u proseku za oko 3 mm nizim u odnosu na visegodisnji prosek. 
</p>

<strong>
AVGUST 2019: Toplotni talasi. Topliji i suvlji avgust.
</strong>
<p style="width:95%">
Srednja minimalna temperatura vazduha u avgustu imace vrednosti iznad visegodisnjeg proseka, pri cemu ce njena vrednost u proseku biti viša za oko 0.5ºS u odnosu na visegodisnji prosek. 
U Beogradu i siroj okolini predvidja se vrednost avgustovske srednje minimalne temperature vazduha od 18.2ºS. 
Srednja maksimalna temperatura vazduha u avgustu bice iznad visegodisnjeg proseka, sa vrednostima u proseku visim za oko 1.7ºS u odnosu na visegodisnji prosek. 
U Beogradu i siroj okolini srednja maksimalna temperatura vazduha tokom avgusta bice oko 30.5ºS. 
Mesečna suma padavina tokom avgusta bice ispod visegodisnjeg proseka sa vrednostima u proseku nizim za oko 15 mm u odnosu na visegodisnji prosek.
</p>
</div>