
<table summary="Podaci meteroloskih stanica- Srbija" id="podaci">

<thead>
  <tr>
       <th style="font-size:16px">Stanica</th>
         <th style="font-size:16px;">Temperatura<br>(°C)</th>
         <th style="font-size:16px;">Pristisak<br>(hPa)</th>
         <th style="font-size:16px;">Pravac<br>vetra<br></th>
         <th style="font-size:16px;">Brzina<br>vetra<br>(m/s)</th>
         <th style="font-size:16px;">Vlaznost<br>(%)</th>
         <th style="font-size:16px;">Toplotni<br>indeks<br></th> 
         <th style="font-size:16px;">Simbol</th>
  </tr>
</thead>  



<tbody>
      <tr> 
         <td style="font-size:16px;">Beograd</td>
          <td style="font-size:16px;">50+</td>
          <td style="font-size:16px;">1001.6</td>
          <td style="font-size:16px;">/</td>
          <td style="font-size:16px;">0</td>
          <td style="font-size:16px;">51</td>
          <td style="font-size:16px;">40</td>
          <td style="font-size:16px;"><img src="../img/vedro.gif" alt="Vedro" width="57" height="36"></td>
       
        </tr>
   
       <tr> 
          <td style="font-size:16px;">Sombor</td>
          <td style="font-size:16px;">35</td>
          <td style="font-size:16px;">1007.7</td>
          <td style="font-size:16px;">WNW</td>
          <td style="font-size:16px;">2</td>
          <td style="font-size:16px;">39</td>
          <td style="font-size:16px;">29</td>
          <td style="font-size:16px;"><img src="../img/uoblacno.gif" alt="Delemicno oblacno" width="57" height="36"></td>
       
         </tr>
   
        <tr> 
         <td style="font-size:16px;">Novi Sad</td>
         <td style="font-size:16px;">33</td>
         <td style="font-size:16px;">1007.9</td>
         <td style="font-size:16px;">N</td>
         <td style="font-size:16px;">5</td>
         <td style="font-size:16px;">42</td>
         <td style="font-size:16px;">30</td>
         <td style="font-size:16px;"><img src="../img/vedro.gif" alt="Pretezno vedro" width="57" height="36"></td>
         </tr>
   
       <tr> 
          <td style="font-size:16px;">Zrenjanin</td>
          <td style="font-size:16px;">30</td>
          <td style="font-size:16px;">1007.3</td>
          <td style="font-size:16px;">N</td>
          <td style="font-size:16px;">3</td>
          <td style="font-size:16px;">48</td>
          <td style="font-size:16px;">29</td>
          <td style="font-size:16px;"><img src="../img/vedro.gif" alt="Pretezno vedro" width="57" height="36"></td>
       
       </tr>
   
       <tr> 
          <td style="font-size:16px;">Kikinda</td>
          <td style="font-size:16px;">32</td>
          <td style="font-size:16px;">1008.3</td>
          <td style="font-size:16px;">N</td>
          <td style="font-size:16px;">5</td>
          <td style="font-size:16px;">45</td>
          <td style="font-size:16px;">29</td>
          <td style="font-size:16px;"><img src="../img/uoblacno.gif" alt="Delemicno oblacno" width="57" height="36"></td>
       
       </tr>
   
   
       <tr> 
          <td style="font-size:16px;">B.Karlovac</td>
          <td style="font-size:16px;">32</td>
          <td style="font-size:16px;">1006.0</td>
          <td style="font-size:16px;">ESE</td>
          <td style="font-size:16px;">5</td>
          <td style="font-size:16px;">42</td>
          <td style="font-size:16px;">30</td>
          <td style="font-size:16px;"><img src="../img/vedro.gif" alt="Vedro" width="57" height="36"></td>
       
       </tr>
   
       <tr> 
          <td style="font-size:16px;">Loznica</td>
          <td style="font-size:16px;">34</td>
          <td style="font-size:16px;">1003.7</td>
          <td style="font-size:16px;">NNW</td>
          <td style="font-size:16px;">2</td>
          <td style="font-size:16px;">58</td>
          <td style="font-size:16px;">31</td>
          <td style="font-size:16px;"><img src="../img/poblacno.gif" alt="Delemicno oblacno" width="57" height="36"></td>
       
      </tr>

        <tr> 
          <td style="font-size:16px;">S.Mitrovica</td>
          <td style="font-size:16px;">33</td>
          <td style="font-size:16px;">1008.4</td>
          <td style="font-size:16px;">N</td>
          <td style="font-size:16px;">3</td>
          <td style="font-size:16px;">45</td>
          <td style="font-size:16px;">29</td>
          <td style="font-size:16px;"><img src="../img/psunacno.gif" alt="Pretezno vedro" width="57" height="36"></td>
   
        </tr>                 
   
       
       </tr>
   </tbody>
   <tfoot>

   <tr>
   <td  colspan="10">Prognoza azurirana: 05.07.2019. 10:23:32</td>
   </tr>
   </tfoot>

</table>

<table summary="Opis pojava" id="opis">
<caption>
<h2>OPIS POJAVA:</h2>
</caption>
<tbody>
   
<tr>
<td><img src="../img/vedro.gif" alt="Vedro" width="57" height="36"></td>
<td>Vedro</td>
<td><img src="../img/mkisa.gif" alt="Moguca Kisa" width="57" height="36"></td>
<td>Moguca Kisa</td>
<td><img src="../img/uoblacno.gif" alt="Umerno oblacno" width="57" height="36"></td>
<td>Umereno Oblacno</td>
</tr>


<tr>
<td><img src="../img/suncano.gif" alt="Suncano" width="57" height="36"></td>
<td>Suncano</td>
<td><img src="../img/kisa.gif" alt="Kisa" width="57" height="36"></td>
<td>Kisa</td>
<td><img src="../img/lkisa.gif" alt="Kisa koja se ledi" width="57" height="36"></td>
<td>Кisa koja se ledi</td>
</tr>


<tr>
<td><img src="../img/psunacno.gif" alt="Pretezno suncano" width="57" height="36"></td>
<td>Pretezno suncano</td>
<td><img src="../img/poblacno.gif" alt="Promenljivo oblacno" width="57" height="36"></td>
<td>Promenljivo oblacno</td>
<td><img src="../img/magla.gif" alt="Magla" width="57" height="36"></td>
<td>Magla</td>
</tr>


<tr>
<td><img src="../img/uoblacno.gif" alt="Malo umereno oblacno" width="57" height="36"></td>
<td>Malo umereno oblacno</td>
<td><img src="../img/plusak.gif" alt="Pljusak" width="57" height="36"></td>
<td>Pljusak</td>
<td><img src="../img/jakvetar.gif" alt="Јак vetar" width="57" height="36"></td>
<td>Jak vetar</td>
</tr>

<tr>
<td><img src="../img/ppljuskovi.gif" alt="Poslepodnevni pljskovi" width="57" height="36"></td>
<td>Poslepodnevni pljuskovi</td>
<td><img src="../img/mpluskovi.gif" alt="Moguci pljuskovi" width="57" height="36"></td>
<td>Moguci pljuskovi</td>
<td><img src="../img/sneg.gif" alt="Sneg" width="57" height="36"></td>
<td>Sneg</td>
</tr>


<tr>
<td><img src="../img/grmljavinaipljusak.gif" alt="Pljusak i grmljavina" width="57" height="36"></td>
<td>Pljusak i grmljavina</td>
<td><img src="../img/mpluskovi.gif" alt="Моguci kratkotrajni pljuskovi" width="57" height="36"></td>
<td>Моguci kratkotrajni pljuskovi</td>
</tr>


<tr>
<td><img src="../img/susnezica.gif" alt="Sesnzica" width="57" height="36"></td>
<td>Susnezica</td>
<td><img src="../img/nepogode.gif" alt="Nepogode" width="57" height="36"></td>
<td>Nepogode</td>
</tr>


<tr>
<td><img src="../img/oblacno.gif" alt="Оblacno" width="57" height="36"></td>
<td>Оblacno</td>
<td><img src="../img/msneg.gif" alt="Мoguc sneg" width="57" height="36"></td>
<td>Moguc sneg</td>
</tr>

</tbody>


</table>