<div class="index">

<table>
<thead>
<tr>
<th style="font-size:12px;">Grad:</th>
<th style="font-size:12px">07.07.2019<br>Nedelja</th>
<th style="font-size:12px">08.07.2019<br>Ponedelajk</th>
<th style="font-size:12px">09.07.2019<br>Utorak</th>
</tr>
</thead>


<tbody>
<tr>
<td style="font-size:13px">Beograd</td>

<td class="uv8" style="font-size:15px;">8</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="uv7" style="font-size:15px;">7</td>
</tr>
<tr>

<td style="font-size:13px">Sombor</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="uv6" style="font-size:15px;">6</td>
</tr>


<tr>
<td style="font-size:13px">Novi Sad</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="uv4" style="font-size:15px;">4</td>
</tr>

<tr>
<td style="font-size:13px">Zrenjanin</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class=" uv8" style="font-size:15px;">8</td>
<td class="uv3" style="font-size:15px;">3</td>
</tr>

<tr>
<td style="font-size:13px">Kikinda</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="uv6" style="font-size:15px;">6</td>
</tr>

<tr>
<td style="font-size:13px">B.Karlovac</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="siva75 uv8" style="font-size:15px;">8</td>
<td class="siva75 uv3" style="font-size:15px;">3</td>
</tr>

<tr>
<td style="font-size:13px">Vrsac</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="uv4" style="font-size:15px;">4</td>
</tr>

<tr>
<td  style="font-size:13px">Loznica</td>
<td class=" uv9" style="font-size:15px;">9</td>
<td class=" uv8" style="font-size:15px;">8</td>
<td class="uv1" style="font-size:15px;">1</td>
</tr>

<tr>
<td  style="font-size:13px">S.Mitrovica</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="uv8" style="font-size:15px;">8</td>
<td class="uv4" style="font-size:15px;">4</td>
</tr>


</tbody>
</table>
</div>